### PR TITLE
Fixed the cookie persistence issue. (Issue #10)

### PR DESCRIPTION
**Pull request by mehrdada**
The cookie expiration date should be set only if the cookie is
persistent, not the other way around.  The previous code did
exactly the opposite.

This is a fix for issue #10

### CODE REVIEW

**Comment by gomifromparis** [comment]
Thanks !

I think AuthenticationCookie as well
        _public bool IsExpired(TimeSpan validity)
        {
            return !Persistent && _issueDate.Add(validity) <= DateTime.UtcNow;
        }_

**Comment by mehrdada** [comment]
Mmm... I think that works as intended as is. Certainly should not get its not operator dropped off, but it would be debatable whether to keep !Persistent at all. I would keep it as is.

**Comment by gomifromparis** [comment]
OK I see, it's because an expired persistent cookie is dropped before by the browser because of its Expires property.
So it never arrives to the server.

As you say, it's debatable to keep the !Persistent. If current time > issue time + validity time, the cookie is expired , whatever its persistency is, shouldn't it ? So this test seems strange..

Thanks.

**Comment by mehrdada** [comment]
I believe I was worried about clock sync issues and decided to err on the side of accepting cookie instead of causing inconvenience for the user when I initially wrote that line, but from a security perspective, it is a good idea to drop !Persistent anyway. Also, I am not sure how well-founded that worry is. I will drop the !Persistent.

**Comment by gomifromparis** [comment]
OK thanks

**Comment by runesoerensen** [comment]
Excellent guys, the pull request looks good - is this ready to be merged Mehrdad?

**Comment by mehrdada** [comment]
I think so!

**Pull request merged**
